# Generated by Django 4.1 on 2022-08-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Data_operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Line_speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(blank=True, default=30000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bottle_size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Production_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_counter_reading', models.PositiveIntegerField(default=0)),
                ('final_counter_reading', models.PositiveIntegerField()),
                ('production_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bbt_no', models.CharField(max_length=6)),
                ('bottle_produced', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.area')),
                ('data_operator', models.ForeignKey(default='Oyom', on_delete=django.db.models.deletion.SET_DEFAULT, to='insight.data_operator')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.line')),
                ('line_manager', models.ForeignKey(default='Oyom', on_delete=django.db.models.deletion.SET_DEFAULT, to='insight.line_manager')),
                ('line_speed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.line_speed')),
                ('product_type', models.ForeignKey(default='no-name', on_delete=django.db.models.deletion.SET_DEFAULT, to='insight.product_type')),
                ('production_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.production_team')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.shift_type')),
                ('team_leader', models.ForeignKey(default='Oyom', on_delete=django.db.models.deletion.SET_DEFAULT, to='insight.team_leader')),
                ('time_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insight.time_period')),
            ],
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('function_failure', models.CharField(max_length=400)),
                ('failure_mode', models.CharField(max_length=400)),
                ('failure_mode_description', models.CharField(max_length=600)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insight.category')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insight.equipment')),
            ],
        ),
    ]
