# Generated by Django 4.1 on 2022-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_alter_insightdata_bottle_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightdata',
            name='deviation_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
