# Generated by Django 4.1 on 2022-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_insightdata_deviation_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='failure_mode',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='deviation',
            name='function_failure',
        ),
        migrations.AddField(
            model_name='equipment',
            name='failure_mode',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='function_failure',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='insightdata',
            name='line_output',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
