# Generated by Django 4.1 on 2022-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_remove_deviation_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('Filler', 'Filler'), ('Bottle washer', 'Bottle washer'), ('Labeller', 'Labeller'), ('EBI', 'EBI'), ('Packer', 'Packer'), ('Unpacker', 'Unpacker'), ('Palletizer', 'Palletizer'), ('Depalletizer', 'Depalletizer'), ('Bottle Conveyor', 'Bottle Conveyor'), ('Crate Conveyor', 'Crate Conveyor')], max_length=100),
        ),
    ]
