# Generated by Django 4.1 on 2022-08-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_remove_equipment_failure_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremode',
            name='function_failure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insight.functionfailure'),
            preserve_default=False,
        ),
    ]
