# Generated by Django 4.1 on 2022-08-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0009_alter_insightdata_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviation',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviation',
            name='failure_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insight.failuremode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviation',
            name='function_failure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insight.functionfailure'),
            preserve_default=False,
        ),
    ]
