# Generated by Django 4.1 on 2022-08-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0010_deviation_duration_alter_deviation_failure_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='bottles_per_carton',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
