# Generated by Django 4.1 on 2022-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0011_product_type_bottles_per_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightdata',
            name='opi',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
