# Generated by Django 4.1 on 2022-08-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0012_insightdata_opi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightdata',
            name='opi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
