# Generated by Django 4.1 on 2022-08-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "insight",
            "0014_rename_initial_counter_reading_insightdata_former_counter_reading_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="insightdata",
            old_name="former_counter_reading",
            new_name="last_counter_reading",
        ),
    ]
