# Generated by Django 4.1 on 2022-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insight",
            "0015_rename_former_counter_reading_insightdata_last_counter_reading",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="insightdata",
            name="opi",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
