# Generated by Django 4.1 on 2022-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0017_alter_insightdata_opi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviation',
            name='details',
        ),
        migrations.AddField(
            model_name='insightdata',
            name='deviation',
            field=models.ManyToManyField(blank=True, to='insight.deviation'),
        ),
    ]
