# Generated by Django 4.1 on 2022-08-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0018_remove_deviation_details_insightdata_deviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insightdata',
            old_name='deviation',
            new_name='deviation_data',
        ),
        migrations.AddField(
            model_name='deviation',
            name='insight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insight.insightdata'),
            preserve_default=False,
        ),
    ]
