# Generated by Django 4.1 on 2022-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_deviation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('Filler', 'Filler'), ('Bottle washer', 'Bottle washer'), ('Labeller', 'Labeller'), ('EBI', 'EBI'), ('Packer', 'Packer'), ('Unpacker', 'Unpacker'), ('Palletizer', 'Palletizer'), ('Depalletizer', 'Depalletizer'), ('Bottle Conveyor', 'Bottle Conveyor'), ('Crate Conveyor', 'Crate Conveyor'), ('unpacker-Bwasher', 'unpacker-Bwasher'), ('Bwasher-fill', 'Bwasher-filler'), ('filler-labeller', 'filler-labeller'), ('labeller-packer', 'labeller-packer')], max_length=100),
        ),
    ]
