# Generated by Django 4.1 on 2022-09-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviation',
            options={'permissions': [('can_view_dev_deployment', 'can view deployment')]},
        ),
    ]
